name: Build and Test
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-build-and-test.yaml@ccm-UID2-5141-fix-no-test-run
    with: 
      java_version: "21"
      skip_tests: true
    secrets: inherit
